### ISSUE TITLE
Broken graphics since 210130 core.

### ISSUE THREAD

**Issue by sirdavid2** [gyurco/MiSTery#10]
A new demo Flexiscroll 2021 (https://www.pouet.net/prod.php?which=89416) works fine only up to 201126 core. Since 210130 the screen is broken right from the start.

**Comment by gyurco** [comment]
Just tried it with 210711, looks good for me.

**Comment by gyurco** [comment]
Probably you have the 68020 CPU selected, which is not for demos. And you cannot choose the FX68K (68000) with older firmware.

**Comment by sirdavid2** [comment]
That could be it. Since which firmware I would be able to choose CPU?

**Comment by gyurco** [comment]
> That could be it. Since which firmware I would be able to choose CPU?

https://github.com/mist-devel/mist-binaries/blob/master/firmware/firmware_210618.txt#L41

You should really use the latest.

**Comment by sirdavid2** [comment]
Everything seems to work fine with the latest firmware and core. Thanks!

**Comment by gyurco** [comment]
Great'
