### ISSUE TITLE
Native support for the cubase dongle

### ISSUE THREAD

**Issue by jotego** [gyurco/MiSTery#11]
As you know cubase was such an important piece of software for the ST that it is still used nowadays by some professionals. Cubase 3.x and Cubase Score versions were never cracked and they require the dongle to operate. 

The dongle itself has been reverse engineered to the point where the [PCB gerber files](https://github.com/gyurco/MiSTery/files/8370180/keystein.zip) are available, the binary stream to program the CPLD is available and what is more important, [the equations for the CPLD](https://www.atari-forum.com/viewtopic.php?p=430485&sid=a6c88e54c0740531cdd63beb050eea17#p430485) are available too. The equations are short and just a few, so it looks like a small effort that users would love.

Could you consider adding direct to support to it in the MiSTery core, please?

**Comment by gyurco** [comment]
Good idea, and it even works!
![cubase](https://user-images.githubusercontent.com/8644936/160657580-3f055bcc-ea26-4e6f-bb23-c04c7400ba8b.jpg)

**Comment by jotego** [comment]
This is HUGE! I must go run tell the DJ guys!

**Comment by gyurco** [comment]
Great! Just don't tell to Steinberg.

**Comment by jotego** [comment]
Already enthusiastically tested by DJ Hardrich. All good! Thank you very much
