### ISSUE TITLE
cubase_dongle has stopped working.

### ISSUE THREAD

**Issue by rampa069** [gyurco/MiSTery#12]
after the demux rework, the cubase dongle is not working....

As a workaround, i have modified the rom_n assign.

wire        rom_n = rom0_n & rom1_n & rom2_n & rom4_n & rom5_n & rom6_n & romp_n;

as rom3_n was trigggering the rom data instead.

**Comment by gyurco** [comment]
Then it'll prevent 128K carts to work.
Seems it still works on MiST, because the cart area is initialized to FF.
The correct workaround would be to have:
```
wire rom_n = rom0_n & rom1_n & rom2_n & (rom3_n | cubase_enable) & rom4_n & rom5_n & rom6_n & romp_n;
```

**Comment by rampa069** [comment]
works fine. thanks.
