### ISSUE TITLE
Not able to compile MiSTery

### ISSUE THREAD

**Issue by solskogen** [gyurco/MiSTery#4]
Error (12006): Node instance "gstmcu" instantiates undefined entity "gstmcu" File: /root/MiSTery/mist_top.v Line: 256
Error (12006): Node instance "gstshifter" instantiates undefined entity "gstshifter" File: /root/MiSTery/mist_top.v Line: 291
Error (12006): Node instance "fx68k" instantiates undefined entity "fx68k" File: /root/MiSTery/mist_top.v Line: 426
Error (12006): Node instance "ikbd" instantiates undefined entity "ikbd" File: /root/MiSTery/mist_top.v Line: 511
Info (144001): Generated suppressed messages file /root/MiSTery/out/mist.map.smsg
Error: Quartus II 32-bit Analysis & Synthesis was unsuccessful. 4 errors, 32 warnings
    Error: Peak virtual memory: 429 megabytes
    Error: Processing ended: Mon Sep  9 10:49:56 2019
    Error: Elapsed time: 00:00:04
    Error: Total CPU time (on all processors): 00:00:04

 /opt/altera/13.1/quartus/bin/quartus_map -v
Quartus II 32-bit Analysis & Synthesis
Version 13.1.4 Build 182 03/12/2014 SJ Web Edition
Copyright (C) 1991-2014 Altera Corporation

**Comment by ojaksch** [comment]
It's till compiling fine at my site:

> Info: Command: quartus_asm mist
> Info (115031): Writing out detailed assembly data for power analysis
> Info (115030): Assembler is generating device programming files
> Info: Quartus II 64-Bit Assembler was successful. 0 errors, 0 warnings
>     Info: Peak virtual memory: 573 megabytes
>     Info: Processing ended: Mon Sep  9 13:05:50 2019
>     Info: Elapsed time: 00:00:03
>     Info: Total CPU time (on all processors): 00:00:03

quartus_map -v
> Quartus II 64-Bit Analysis & Synthesis
> Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
> Copyright (C) 1991-2013 Altera Corporation

Wasn't there a note anywhere that 13.0.x was the "the last version to support Cyclone II and earlier FPGAs"?

**Comment by solskogen** [comment]
13.1 if you want to believe Intel's site: https://www.intel.com/content/www/us/en/programmable/downloads/download-center.html

**Comment by solskogen** [comment]
MiST is Cyclone III, unless I'm very mistaken.

**Comment by solskogen** [comment]
https://github.com/mist-devel/mist-board/wiki/HowToCompileTheCore

13.1 should work (I can compile the old Mist core)

**Comment by ojaksch** [comment]
> MiST is Cyclone III, unless I'm very mistaken.

> https://github.com/mist-devel/mist-board/wiki/HowToCompileTheCore
> 13.1 should work (I can compile the old Mist core)

Yes, you're absolutely right. And this is the interesting point: Why is the 13.0.x/64-Bit working, but not the 13.1.x/32-Bit?

**Comment by ojaksch** [comment]
Did another test with 13.1.0 this time. No errors encountered.

> Info: Command: quartus_asm mist
> Info (115031): Writing out detailed assembly data for power analysis
> Info (115030): Assembler is generating device programming files
> Info: Quartus II 64-Bit Assembler was successful. 0 errors, 0 warnings
>     Info: Peak virtual memory: 634 megabytes
>     Info: Processing ended: Tue Sep 10 07:52:56 2019
>     Info: Elapsed time: 00:00:03
>     Info: Total CPU time (on all processors): 00:00:03

quartus_map -v

> Quartus II 64-Bit Analysis & Synthesis
> Version 13.1.0 Build 162 10/23/2013 SJ Web Edition
> Copyright (C) 1991-2013 Altera Corporation

I can see that you're using v13.1.4/32-Bit, but can't find any refference to this version at [Intel's download site](http://fpgasoftware.intel.com/13.1/?edition=web), where 13.1.0 is the latest version available for Linux and Windows systems.

**Comment by gyurco** [comment]
Probably you forgot to update submodules:
git submodule init
git submodule update
...or somethings similar, just wrote it from memory

**Comment by solskogen** [comment]
That did it, @gyurco 

@ojaksch I've added Update 4
