### ISSUE TITLE
Problems with disk swapping in some games

### ISSUE THREAD

**Issue by foxp4v** [gyurco/MiSTery#6]
Hello, i think i found a bug, with some games image (Sensibile Soccer, all versions, Cannon Fodder and partially The Chaos Engine, all from TOSEC set) when Is prompted to insert the second disk and you do that, it's like you've put nothing into the drive, the same behavior if you put both disks in the two drives at boot, the only games of the above mentioned that works Is The Chaos Engine, the other ones keep asking for disk two. The bug Is present also in the MiSTer version of the core. The same games images works perfectly in Hatari on Windows.
Thank you for your time.

**Comment by gyurco** [comment]
I'll look at this ASAP

**Comment by gyurco** [comment]
Should be fixed in the newest release.
