### ISSUE TITLE
Broken ST since 210130 core?

### ISSUE THREAD

**Issue by sirdavid2** [gyurco/MiSTery#9]
My ST config with TOS 1.0 keeps rebooting every 2 seconds on 210130 and 210711 cores. It works ok up to 201126. STE with TOS 1.06 or later starts and works. All that with 201011 firmware, MiSTery doesn't work at all for me under firmware 201122 or later.

**Comment by gyurco** [comment]
Do you have an original MiST? Or a clone?
This looks similar to https://github.com/gyurco/MiSTery/issues/8

**Comment by sirdavid2** [comment]
I think it's original, v. 1.3 without MIDI. The board looks the same as https://github.com/mist-devel/mist-board/wiki/TheBoard

**Comment by gyurco** [comment]
68020 CPU doesn't seem to work in ST mode. Note that ST line never intended to have a 68020, so it's more or less expected.

**Comment by gyurco** [comment]
Also, you must revisit, reset and resave the core settings in the menu if you switch to a recent firmware, as the config format changed.

**Comment by sirdavid2** [comment]
Resetting and resaving settings helped. Thanks!
